### ISSUE TITLE
Congratulations

### ISSUE THREAD

**Issue by PBhadoo** [prebid/currency-file#1]
Your Project contains 2 files and is ranked #1 (shown as #0 at jsDelivr) at jsDelivr CDN.

Here are few batches.

https://data.jsdelivr.com/v1/stats/packages

https://www.jsdelivr.com/package/gh/prebid/currency-file

![](https://data.jsdelivr.com/v1/package/gh/prebid/currency-file/badge/rank)

![](https://data.jsdelivr.com/v1/package/gh/prebid/currency-file/badge/year)

![](https://data.jsdelivr.com/v1/package/gh/prebid/currency-file/badge/month)

![](https://data.jsdelivr.com/v1/package/gh/prebid/currency-file/badge/week)

![](https://data.jsdelivr.com/v1/package/gh/prebid/currency-file/badge/day)

**Comment by huhuhang** [comment]
Shocked, why so many requests? 🤯

**Comment by bretg** [comment]
Good to know. This is why Prebid is proud to be a monthly sponsor of jsdelivr.
